# Generated by Django 4.2.1 on 2023-09-22 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_service.products'),
        ),
    ]
